### ISSUE TITLE
Shockwave removal

### ISSUE THREAD

**Issue by Ziggylata** [TheGrandArchives/DS3CommunityPatch#11]
First off, ill explain that because of the netcode and latency against certain opponents, shockwave on long weapons like yhorms machete and other weapons makes spacing an absolute nightmare. With yhorms specifically, its so long and fast enough that by the time the shockwave is over for you, they might already be starting their swing and you wont have any opening to attack. It makes the weapons very hard to fight against and rather easy to use, assuming you dont run out of stamina. Even long weapons like spears are unable to get in there without being destroyed.

When it comes to greataxes, their downside was supposed to be their reach. They had alright speed and great damage and thats why they were short and why a shockwave would make sense, but by giving a long greataxe like yhorms, you suddenly get issues where the weapon is just too hard to space against.

This will especially become an issue if greataxes get their 2h r1 two hit combo back, if possible this needs to be removed, at least on the longer weapons.

**Comment by TheGrandArchives** [comment]
I understand where you're coming from but gonna hold off on this for a bit, we might see in the future
