### ISSUE TITLE
Shield Stabs

### ISSUE THREAD

**Issue by Ziggylata** [TheGrandArchives/DS3CommunityPatch#12]
Stabbing behind a shield is actually worse than getting hit in the face. You take 70% of the damage of the actual attack and probably get shield-broken unless you have a greatshield, the attack probably doesnt come out at all and then you also probably get riposted by the person youre fighting. 
I understand sitting behind your shield and poking is a bit annoying but to make it worse than even **just getting hit in the face**, I really have to wonder who made this game and why.

Please fix this.

**Comment by TheGrandArchives** [comment]
done
