### ISSUE TITLE
Big Whiny Post By a Good Player

### ISSUE THREAD

**Issue by shieldpoke** [TheGrandArchives/DS3CommunityPatch#19]
[Whiny_Post.jpg.xlsx](https://github.com/TheGrandArchives/DS3CommunityPatch/files/1654515/Whiny_Post.jpg.xlsx)

**Comment by shieldpoke** [comment]
Oh yeah, don't nerf washing pole, gets dumpstered by shields anyway and even without a shield, most meta weapons still dumpster WP. Also please add poise, and if you want to test it out, instant backstabs as well. It's up to you honestly for the IBS part.

**Comment by TheGrandArchives** [comment]
go away

**Comment by Ziggylata** [comment]
That whole grid image discussing everything being changed isnt completely unfounded and theres a lot of stuff that I think is accurate but there is a severe amount of whine and favoritism going on.

Also, the reason to ever not use the upgraded version of a spell is the cost to cast it.

**Comment by shieldpoke** [comment]
I did warn you about the whine. I mean yeah, but would you ever use soul spear over crystal soul spear? Sure it costs less, but it's simply not good enough to waste an attunement slot for. The exception is soul mass, but the express purpose of that move is to spam it. The purpose of spells such as CBV and CSS is to do tons of damage. Soul spear and fireball are in an awkward middle spot that is nigh impossible to fix. The problem is only inflamed with fireball, since you have fire orb and black fire orb and the one that has lava when it lands. Soul spear could be fixed, but when you have half a million variations of the same goddamn spell, it's just not worth it to fix it.

**Comment by Ziggylata** [comment]
To be honest, thats an issue I have with the mana system over the numbered system. You can get 5 crystal soul spears or like 40 soul arrows.
5 to 40 is a pretty considerable reason to take a weaker spell over a stronger one. Its a shame they brought back the mana bar instead of keeping that system.
