### ISSUE TITLE
Suggetions: Flash Sword Melee bonus and Weapon Catalyst infusion emulation.

### ISSUE THREAD

**Issue by SpartanHexus** [TheGrandArchives/DS3CommunityPatch#25]
Suggestions:

Make melee spells do bonus damage with weapon catalysts, with flash sword it should be easy since the spell fires two attacks: the spell itself and the parriable hit with the physical part of the catalyst which has its attack with hitsource type set as 0, making its damage being based on the catalyst elemental and physical damage instead of the spellbuff. There is a different attack ID for flash sword physical hit on every catalyst so you can give different scalings to every catalyst. This would also indirectly make a new mechanic for weapon catalysts since you have to be closer to deal more damage as you need to hit the physical and the spell for the full damage which will increase the chances of getting parried.

Let us emulate infusions on the weapon catalysts, activate the script for the weapon you want and it will work as if it was infused, with the 4 main elemental infusions altering only scaling and base damage and the 4 weaker elemental infusions altering what can be cast with them, my scripts does it as follow:

Crystal Cleric candlestick: increases the elemental damage, its better than simple longsword but worse than crystal longsword at 60 int.

Chaos/Dark Cleric candlestick: Sorceries scales with int and faith, the catalyst deals dark/fire damage instead of magic again worse than dark/chaos longsword but yet not bad, scales well with sorcery but not so well with dark sorceries.

Lightning Cleric candlestick: Scales with faith, deals lightning damage instead of magic. Should have the same toal AR as with crystal cleric candlestick on 60 faith.

Blessed Cleric Candlestick, no hp regen though: Deals pure physical damage scaling on faith, casts only miracles and has saint talisman unfaltering prayer (the weakest unfaltering prayer).

Fire Cleric Candlestick: same as with chaos candlestick but with less damage and it casts pyromancies.

Deep Cleric Candlestick: same as with dark candlestick but it scales better for dark sorceries. On non sorceries weapon catalyst, it would cast sorceries instead.

Simple: Same as crystal candlestick but with less damage, fp regen on catalysts that already casts sorceries. On another weapon catalyst, the rose of ariandel for example, it would allow sorceries to be cast.

Edit: Since i made this thread anyway gonna include more suggestions:

Replace the regular sorcerer staff weapon art with weapon skill, so we can have a catalyst that lets us use weapon arts, do the same with the ashes of ariandel pyro flame and with the first cleric chime.

Add fp regen to ashen estus ring.

**Comment by SpartanHexus** [comment]
The script on cleric candlestick, nothing you guys can't do it better if you decide to do it, i also did heysel pick, immolation tinder and golden ritual spear but they're ugly looking for now, save the text from this as a ct file: https://pastebin.com/D4BiHQjb It doesn't change the candlestick name though.

**Comment by TheGrandArchives** [comment]
This sounds autistically difficult and even more autistically pointless. Make additional issues for other suggestions, it keeps things simpler.
