### ISSUE TITLE
Remove the pike class

### ISSUE THREAD

**Issue by shieldpoke** [TheGrandArchives/DS3CommunityPatch#26]
Literally, no reason for them to exist, you can just lower the damage of the pikes and give them regular spear movesets so they aren't useless.

**Comment by shieldpoke** [comment]
The only exception to this would be greatlance, but that needs speed buffs regardless.

**Comment by Ziggylata** [comment]
Lothric Knight Long Spear is waifu weapon dont you dare touch it.

**Comment by TheGrandArchives** [comment]
I doubt this is going to happen.
