### ISSUE TITLE
Dont nerf defenses on light armor

### ISSUE THREAD

**Issue by shieldpoke** [TheGrandArchives/DS3CommunityPatch#29]
No need for nerfs at this point. Already never used save for fashion. Instead you should just increase defense slightly, and keep the buffs already planned.

**Comment by Ziggylata** [comment]
How about we do anyway, allowing us to make armor more rewarding as you go up in weight.

**Comment by shieldpoke** [comment]
Or just make heavier armor stronger and NOT nerf the weaker armor? Is that so hard to grasp?
