### ISSUE TITLE
Patch Confirmations across random PvP

### ISSUE THREAD

**Issue by Ziggylata** [TheGrandArchives/DS3CommunityPatch#4]
If you were to encounter someone in PvP that wasnt using the patch for example, they would have the retarded number of iframes and the absurdly low stamina cost. Perhaps some sort of way to get rid of the people that arent using the patch would help? Someone in the discord even suggested cursing people who arent using the patch (I assume that would mean that the patch players would be immune) or maybe a visual effect on people who are using the patch?

The point is, people with the patch go in, people without go out.

**Comment by TheGrandArchives** [comment]
I agree with the idea of making patch users identifiable, but I haven't yet heard a sensible suggestion as to how as cursing is shitty

**Comment by TheGrandArchives** [comment]
added to the list either way
