### ISSUE TITLE
Infusions and buffs

### ISSUE THREAD

**Issue by Ziggylata** [TheGrandArchives/DS3CommunityPatch#8]
How about those infusions actually mattering? I still think refined should fundimentally be the best damage infusion because its using the most stats, however sharp and heavy are a little bit too weak and the rest of the infusions are generally terrible.
Also, infused weapons should be able to be buffed as well. Fire weapons with fire buffs, magic weapons with magic buffs and so on. Id also like to see more unique weapons be able to be buffed as well (within reason, I dont think the dancers swords being buffed when they get patched to be better in general would be a good idea, itd probably end up being pretty op pretty fast.)

**Comment by Ultimegiddo** [comment]
This could be fine within reason since buffs are temporary and can be duel charmed.

**Comment by TheGrandArchives** [comment]
ba dum bum done
